### ISSUE TITLE
Something broke in publish for inner content HDAs

### ISSUE THREAD

**Issue by mswindler** [byu-animation/dccpipe#102]
Publishing via opmenu in Hou for a modify/material node now breaks it and when it's imported again, it's missing modify and material.

**Comment by semagnum** [comment]
Just a note of the error:
```
Traceback (most recent call last):
  File ".../pipe/tools/houtools/publisher/publisher.py", line 395, in publish_hda
    modify = inside.node("modify")
AttributeError: 'NoneType' object has no attribute 'node'
```

**Comment by semagnum** [comment]
Here's the error for reference (and I got it without using the opmenu as well):
```
Traceback (most recent call last):
  File "./pipe/tools/houtools/publisher/publisher.py", line 395, in publish_hda
    modify = inside.node("modify")
AttributeError: 'NoneType' object has no attribute 'node'
```

**Comment by semagnum** [comment]
After I export the material, it does so without errors, but this error comes when importing:
```
Traceback (most recent call last):
  File "/users/guest/s/smagnuss/SaltRepo/spencerPipe/dccpipe/pipe/tools/houtools/cloner/cloner.py", line 159, in asset_results
    node, created_instances =  Assembler().create_hda(filename, body=self.body, department_paths=department_paths)
  File "/users/guest/s/smagnuss/SaltRepo/spencerPipe/dccpipe/pipe/tools/houtools/assembler/assembler.py", line 564, in create_hda
    content_hda_filepath = department_paths[department]
KeyError: 'modify'
```
